import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";




const degular = localFont({
  src: [
    {
      path: './fonts/DegularDisplay-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/DegularDisplay-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/DegularDisplay-Semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/DegularDisplay-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-degular",
  display: 'swap',
});




export const metadata: Metadata = {
  title: "Okjeri dashboard",
  description: "Generated by okjeri-dashboard",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <main className={degular.className}>
          {children}
        </main>
      </body>
    </html>
  );
}
