export const pageTitles: Record<string, string> = {
  "/dashboard": "Dashboard Overview",
  "/users": "Users",
  "/provider": "Providers",
  "/userReviewRequest": "Users review requests",
  "/providerReviewRequest": "Provider review requests",
  "/bookings": "Manage bookings",
  "/services": "Services",
  "/requestedServices": "Requested services",
  "/transactions": "Transactions",
  "/payouts": "Payout requests",
  "/referralManagement": "Referral management",
  "/allReferrals": "All referrals",
  "/disputeManagement": "Dispute management",
  "/dispute_fom_user": "Dispute details",
  "/promotions": "Promotions",
  "/boostControl": "Boosted profiles",
  "/pricingControl": "Pricing control",
  "/boostingRequests": "Boosting requests",
  "/changePassword": "Change password",
  "/terms&Conditions": "Terms & Conditions",
  "/aboutUs": "About Us",
  "/faq": "FAQ",
  "/notification": "Notifications",
};